[QC]
# These config parameters determine how QC samples are distributed on the plate. 

# QC round = a sequence of QC samples included before and/or 
#           after a sequence of analytical (specimen) samples

# should first well(s) be QC a QC round?
start_with_QC_round = true
# how many non-QC samples to analyze until we start a round of QC samples? 
run_QC_after_n_specimens = 11 

    [QC.names] # key names and description of QC samples we will use
    #
    EC = "EC: External_Control_(matrix)"
    PB = "PB: Paper_Blank"
    PO = "PO: Pooled_specimens"

    [QC.scheme] # when and how often to use QC samples in QC rounds
    #
    # every_n_round = how often should we include the QC sample in a QC round?
    # introduce_in_round = when should the QC sample be run for the first time? 0 = all rounds.
    # position_in_round = which order should the QC sample have when it is included in a QC run? 

    EC = {every_n_rounds = 1, introduce_in_round = 0, position_in_round = 2}
    PB = {every_n_rounds = 2, introduce_in_round = 1, position_in_round = 1}
    PO = {every_n_rounds = 2, introduce_in_round = 2, position_in_round = 1}

